### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Xoma163** [AlexSat/jellyfin-sort-by-raw-name-plugin#1]
Hello!

I installed plugin and nothing happend. How I can activate it or smth? 

Thanks

**Comment by AlexSat** [comment]
Hello!
It becomes active after installation. No additional action required.
Could you write, please, Jellyfin version and attach two screenshots: library content before installation and after?

**Comment by AlexSat** [comment]
@Xoma163 Hello! Fixed 👍
